from .user import *
from .course import *
from .staff import *
from .semester import *
from .gradeStats import *
from .allocation import *
from .programme import *
from .coursegroup import *
from .credittype import *
from .prerequisite import *
from .programmecourse import *
from .markingexpense import *